In [1]:
import pandas as pd

In [56]:
# import url directly only show 1000 rows 
# please download it from NYC open data portal
file_path1 = '/Users/yokij/Desktop/NYPD_Arrests_Data__Historic__20231116.csv'
data1 = pd.read_csv(file_path1)
data1 = data1.drop(columns=['Lon_Lat'])
file_path2 = '/Users/yokij/Desktop/NYPD_Arrest_Data__Year_to_Date__20231116.csv'
data2 = pd.read_csv(file_path2)
data2 = data2.drop(columns=['New Georeferenced Column'])
df = pd.concat([data1, data2])
df.head()

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude
0,236791704,11/22/2021,581.0,NaN,NaN,NaN,PL 2225001,M,M,28,0.0,45-64,M,BLACK,997427.0,230378.0,40.799009,-73.952409
1,237354740,12/04/2021,153.0,RAPE 3,104.0,RAPE,PL 1302502,F,B,41,0.0,25-44,M,WHITE HISPANIC,1013232.0,236725.0,40.816392,-73.895296
2,236081433,11/09/2021,681.0,"CHILD, ENDANGERING WELFARE",233.0,SEX CRIMES,PL 2601001,M,Q,113,0.0,25-44,M,BLACK,1046367.0,186986.0,40.679700,-73.776047
3,32311380,06/18/2007,511.0,"CONTROLLED SUBSTANCE, POSSESSION 7",235.0,DANGEROUS DRUGS,PL 2200300,M,Q,27,1.0,18-24,M,BLACK,NaN,NaN,NaN,NaN
4,192799737,01/26/2019,177.0,SEXUAL ABUSE,116.0,SEX CRIMES,PL 1306503,F,M,25,0.0,45-64,M,BLACK,1000555.0,230994.0,40.800694,-73.941109

In [52]:
#delete data if its category is NaN
df = df[df['KY_CD'].notna()] #KY_CD is more general than PD_CD
df = df[df['LAW_CAT_CD'].notna()] #This records Three categories(felony,misdemeanor and violation)
# Filter the DataFrame to keep records from 2014 to 2023
df['ARREST_DATE'] = pd.to_datetime(df['ARREST_DATE'])
df = df[(df['ARREST_DATE'].dt.year >= 2014) & (df['ARREST_DATE'].dt.year <= 2023)]
df = df.sort_values(by='ARREST_DATE')

In [55]:
#Check and Display rows with missing values
rows_with_missing_values = df.isnull().any(axis=1)
missing_value_records = df[rows_with_missing_values]
print(missing_value_records)

Empty DataFrame
Columns: [ARREST_KEY, ARREST_DATE, PD_CD, PD_DESC, KY_CD, OFNS_DESC, LAW_CODE, LAW_CAT_CD, ARREST_BORO, ARREST_PRECINCT, JURISDICTION_CODE, AGE_GROUP, PERP_SEX, PERP_RACE, X_COORD_CD, Y_COORD_CD, Latitude, Longitude]
Index: []

In [48]:
df.head()

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude
2341174,94272239,2014-01-01,114.0,OBSTR BREATH/CIRCUL,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1211100,M,Q,105,0.0,45-64,M,AMERICAN INDIAN/ALASKAN NATIVE,1058398.0,189402.0,40.686239,-73.732645
2363804,94266293,2014-01-01,625.0,"DISORDERLY CONDUCT SUBD 1,2,3,4,5,6,7",572.0,DISORDERLY CONDUCT,PL 2402007,V,K,62,0.0,18-24,M,WHITE HISPANIC,983457.0,165616.0,40.621262,-74.002858
2351589,94266296,2014-01-01,567.0,"MARIJUANA, POSSESSION 4 & 5",235.0,DANGEROUS DRUGS,PL 2211001,M,K,77,0.0,45-64,M,BLACK,1001507.0,184056.0,40.671859,-73.937791
2336068,94272155,2014-01-01,439.0,"LARCENY,GRAND FROM OPEN AREAS,UNCLASSIFIED",109.0,GRAND LARCENY,PL 1553004,F,M,9,0.0,25-44,M,WHITE HISPANIC,987082.0,205128.0,40.729713,-73.989783
2336088,94266343,2014-01-01,115.0,RECKLESS ENDANGERMENT 2,355.0,OFFENSES AGAINST THE PERSON,PL 1202000,M,M,17,0.0,18-24,M,WHITE,992129.0,214768.0,40.756170,-73.971562